### ISSUE TITLE
WIP: MultiFile fork

### ISSUE THREAD

**Issue by pellaeon** [pellaeon/SingleFileZ#1]
This issue tracks my work to modify SingleFileZ to write multiple files.

## Strategy
- Start with making a `multifile` CLI tool, by creating a new code path `mutlifile` -> `cli/single-file-cli-api.js` -> multifile backend -> multifile injectedscript
- Fetch resources from outside the browser using Playwright's [APIRequestContext](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get)

## TODO

- [x] create new multifile executable script by copying the original `single-filez`
- [x] create new backend from playwright-firefox
- [x] find a way to turn off options.compressContent in injected script
- [x] implement fetch resources content using APIRequestContext in backend
- [x] create new `cli/single-file-cli-api.js` and implement folder and resources writing
